version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
      
  front-end:
    image: bradfield7/project2-front-end:latest
    build: ./front-end

  name-generator:
    image: bradfield7/project2-name-generator:latest
    build: ./name-generator
    deploy:
      replicas: 2


  league-generator:
    image: bradfield7/project2-league-generator:latest
    build: ./league-generator
    deploy:
      replicas: 2


  club-generator:
    image: bradfield7/project2-club-generator:latest
    build: ./club-generator
    deploy:
      replicas: 2