---
# tasks file for swarm-worker

- name: "join worker"
  docker_swarm:
    state: join
    advertise_addr: swarmworker
    join_token: "{{ hostvars['swarmmanager']['info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'swarmmanager:2377' ]