---
# tasks file for swarm-worker

- name: "swarm worker"
  docker_swarm:
    state: join
    advertise_addr: swarmworker
    join_token: "{{ hostvars['swarmmaster']['info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'swarmmaster:2377' ]