all:
  children:
    managers:
      hosts:
        swarmmanager:
    workers:
      hosts:
        swarmworker:
        
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: '~/.ssh/ansible_id_rsa'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'